
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GREATERTH = 23;
  public static final int UMINUS = 20;
  public static final int Q = 11;
  public static final int LPAREN = 5;
  public static final int INT = 10;
  public static final int RBRAC = 19;
  public static final int MINUS = 3;
  public static final int REF = 12;
  public static final int RPAREN = 6;
  public static final int NOT = 27;
  public static final int SEMICOLON = 8;
  public static final int AND = 28;
  public static final int INTCONST = 35;
  public static final int NIL = 33;
  public static final int OR = 29;
  public static final int COMMA = 31;
  public static final int PLUS = 2;
  public static final int LESSEQ = 24;
  public static final int ASSIGN = 30;
  public static final int IF = 13;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int error = 1;
  public static final int MUTABLE = 32;
  public static final int IDENT = 36;
  public static final int EQ = 21;
  public static final int LESSTH = 25;
  public static final int TIMES = 4;
  public static final int LBRACE = 16;
  public static final int ELSE = 14;
  public static final int WHILE = 15;
  public static final int RBRACE = 17;
  public static final int GREATEREQ = 22;
  public static final int LBRAC = 18;
  public static final int PRINT = 9;
  public static final int NOTEQ = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "RETURN",
  "SEMICOLON",
  "PRINT",
  "INT",
  "Q",
  "REF",
  "IF",
  "ELSE",
  "WHILE",
  "LBRACE",
  "RBRACE",
  "LBRAC",
  "RBRAC",
  "UMINUS",
  "EQ",
  "GREATEREQ",
  "GREATERTH",
  "LESSEQ",
  "LESSTH",
  "NOTEQ",
  "NOT",
  "AND",
  "OR",
  "ASSIGN",
  "COMMA",
  "MUTABLE",
  "NIL",
  "DOT",
  "INTCONST",
  "IDENT"
  };
}

