package parser;

import java.util.*;
import java.io.*;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import java_cup.runtime.ComplexSymbolFactory;

import ast.*;
import interpreter.Interpreter;

parser code {: 
  Lexer lexer;

  public Parser(Lexer lex, ComplexSymbolFactory sf) {
    super(lex, sf);
    lexer = lex;
  }

  public void report_fatal_error(String message, Object info) {
    Interpreter.fatalError(message + " (" + info + ")", Interpreter.EXIT_PARSING_ERROR);
  }

  ast.Location loc(int line, int column) {
    return new ast.Location(line, column);
  }

:};

terminal PLUS, MINUS, TIMES, LPAREN, RPAREN, RETURN, SEMICOLON, PRINT;
terminal INT, Q, REF, IF, ELSE, WHILE, LBRACE, RBRACE, LBRAC, RBRAC;
terminal UMINUS;
terminal EQ, GREATEREQ, GREATERTH, LESSEQ, LESSTH, NOTEQ, NOT, AND, OR;
terminal ASSIGN, COMMA;
terminal MUTABLE, NIL, DOT;
terminal Long  INTCONST;
terminal String IDENT;

non terminal Program         program;
non terminal MainFunction    main;
non terminal FuncDef         funcDef;
non terminal FuncDefList     funcDefList;
non terminal FormalDeclList  formalDeclList;
non terminal FormalDeclList  neFormalDeclList;
non terminal VarDecl         varDecl;
non terminal StmtList        stmtList;
non terminal Stmt            stmt;
non terminal Cond            condition;
non terminal Type            type;         
non terminal Expr            expr;
non terminal ExprList        exprList;
non terminal ExprList        neExprList;
non terminal BinaryExpr      binaryExpr;
non terminal UnaryExpr       unaryExpr;

precedence left ELSE;
precedence left OR;
precedence left AND;
precedence left NOT;
precedence left EQ, GREATEREQ, GREATERTH, LESSEQ, LESSTH, NOTEQ;
precedence left DOT;
precedence left PLUS, MINUS;
precedence left TIMES;
precedence left UMINUS;

start with program;

program ::= funcDefList:fdl
            {: RESULT = new Program(fdl, loc(fdlleft, fdlright)); :}
         ;

funcDefList ::= funcDef:fd funcDefList:fdl
            {: RESULT = new FuncDefList(fd, fdl, loc(fdleft, fdright)); :}
      |   /*empty*/
            {: RESULT = null; :}
         ;

funcDef ::= varDecl:v1 LPAREN formalDeclList:Fdl RPAREN LBRACE stmtList:sl RBRACE
            {: RESULT = new FuncDef(v1, Fdl, sl, loc(slleft, slright)); :}
         ;

formalDeclList ::= neFormalDeclList:nfdl
            {: RESULT = nfdl; :}
      |  /* empty */
            {: RESULT = null; :}
         ;

neFormalDeclList ::= varDecl:v COMMA neFormalDeclList:nfdl
            {: RESULT = new FormalDeclList(v, nfdl, loc(vleft, vright)); :}
      | varDecl:v
            {: RESULT = new FormalDeclList(v, null, loc(vleft,vright)); :}
         ;

varDecl ::= type:t IDENT:id
            {: RESULT = new VarDecl(false, t, id, loc(tleft, tright)); :}
         |
            MUTABLE type:t IDENT:id
            {: RESULT = new VarDecl(true, t, id, loc(tleft, tright)); :}
         ;        

type ::= INT:e
            {: RESULT = new Type(Type.INT, loc(eleft, eright)); :}
      |  Q:e
            {: RESULT = new Type(Type.Q, loc(eleft, eright)); :}
      |  REF:e
            {: RESULT = new Type(Type.REF, loc(eleft, eright)); :}
         ;

stmtList ::= stmt:s stmtList:sl
            {: RESULT = new StmtList(s, sl, loc(slleft, slleft)); :}
      |  /*empty*/    
            {:RESULT = null; :}
         ; 
         
stmt ::= varDecl:v ASSIGN expr:e SEMICOLON
            {: RESULT = new VarDeclStmt(v, e, loc(vleft, vleft)); :}
      |   IDENT:id ASSIGN expr:e SEMICOLON
            {: RESULT = new AssignStmt(id, e, loc(idleft, idleft)); :}
      |   IF LPAREN condition:c RPAREN stmt:s
            {:RESULT = new IfStmt(c, s, loc(cleft, cleft)); :}
      |   IF LPAREN condition:c RPAREN stmt:s1 ELSE stmt:s2
            {:RESULT = new IfElseStmt(c, s1, s2, loc(cleft, cright)); :}
      |   WHILE LPAREN condition:c RPAREN stmt:s
            {:RESULT = new WhileStmt(c, s, loc(cleft, cright)); :}
      |   IDENT:id LPAREN exprList:eList RPAREN SEMICOLON
            {:RESULT = new CallStmt(id, eList, loc(idleft, idright)); :}
      |   PRINT expr:e SEMICOLON
            {:RESULT = new PrintStmt(e, loc(eleft, eright)); :}
      |   RETURN expr:e SEMICOLON
            {:RESULT = new ReturnStmt(e, loc(eleft, eright)); :}
      |   LBRACE stmtList:sl RBRACE
            {:RESULT = sl; :}
         ; 

condition ::= expr:e1 LESSTH expr:e2
         {: RESULT = new CondRelation(e1, CondRelation.LESSTH, e2, loc(e1left, e1right)); :}
      |  expr:e1 GREATERTH expr:e2
         {: RESULT = new CondRelation(e1, CondRelation.GREATERTH, e2, loc(e1left, e1right)); :}
      |  expr:e1 EQ expr:e2
         {: RESULT = new CondRelation(e1, CondRelation.EQ, e2, loc(e1left, e1right)); :}
      |  expr:e1 NOTEQ expr:e2 
         {: RESULT = new CondRelation(e1, CondRelation.NOTEQ, e2, loc(e1left, e1right)); :}
      |  expr:e1 LESSEQ expr:e2
         {: RESULT = new CondRelation(e1, CondRelation.LESSEQ, e2, loc(e1left, e1right)); :}
      |  expr:e1 GREATEREQ expr:e2
         {: RESULT = new CondRelation(e1, CondRelation.GREATEREQ, e2, loc(e1left, e1right)); :}
      |  condition:c1 AND condition:c2
         {: RESULT = new LogicCondition(c1, LogicCondition.AND, c2, loc(c1left, c1right)); :}
      |  condition:c1 OR condition:c2
         {: RESULT = new LogicCondition(c1, LogicCondition.OR, c2, loc(c1left, c1right)); :}
      |  NOT condition:c1
         {: RESULT = new LogicCondition(c1, LogicCondition.NOT, null, loc(c1left, c1right)); :}
      |  LPAREN condition:c RPAREN
         {: RESULT = c; :}
      ;

expr ::= INTCONST:c
         {: RESULT = new ConstExpr(c, loc(cleft, cright)); :}
      |   IDENT:c
         {: RESULT = new VarExpr(c, loc(cleft, cright)); :}
      |  unaryExpr:e
         {: RESULT = e; :}
      |  binaryExpr:e
         {: RESULT = e; :}
      |  LPAREN expr:e RPAREN
         {: RESULT = e; :} 
      |  IDENT:id LPAREN exprList:el RPAREN
         {: RESULT = new CallExpr(id, el, loc(idleft, idright)); :} 
      |  NIL:n
         {: RESULT = new ConstExpr(loc(nleft, nright)); :}
      |  LPAREN type:t RPAREN expr:e
         {: RESULT = new CastExpr(t, e, loc(tleft, tright)); :}
      ;

exprList ::= neExprList:e
         {: RESULT = e; :}
      |   /*empty*/
         {: RESULT = null; :}
      ;

neExprList ::= expr:e COMMA neExprList:eList
         {: RESULT = new ExprList(e, eList , loc(eleft, eright)); :}
      |   expr:e
         {: RESULT = new ExprList(e, null , loc(eleft, eright)); :}
      ;

binaryExpr ::= expr:e1 PLUS expr:e2
               {: RESULT = new BinaryExpr(false, e1, BinaryExpr.PLUS, e2, loc(e1left, e1right)); :}
            |  expr:e1 MINUS expr:e2
               {: RESULT = new BinaryExpr(false, e1, BinaryExpr.MINUS, e2, loc(e1left, e1right)); :}
            |  expr:e1 TIMES expr:e2
               {: RESULT = new BinaryExpr(false, e1, BinaryExpr.TIMES, e2, loc(e1left, e1right)); :}
            |  expr:e1 DOT expr:e2
               {: RESULT = new BinaryExpr(false, e1, BinaryExpr.DOT, e2, loc(e1left, e1right)); :}
            | LBRAC expr:e1 PLUS expr:e2 RBRAC
               {: RESULT = new BinaryExpr(true, e1, BinaryExpr.PLUS, e2, loc(e1left, e1right)); :}
            |  LBRAC expr:e1 MINUS expr:e2 RBRAC
               {: RESULT = new BinaryExpr(true, e1, BinaryExpr.MINUS, e2, loc(e1left, e1right)); :}
            |  LBRAC expr:e1 TIMES expr:e2 RBRAC
               {: RESULT = new BinaryExpr(true, e1, BinaryExpr.TIMES, e2, loc(e1left, e1right)); :}
            |  LBRAC expr:e1 DOT expr:e2 RBRAC
               {: RESULT = new BinaryExpr(true, e1, BinaryExpr.DOT, e2, loc(e1left, e1right)); :}
            ;

unaryExpr ::= MINUS expr:e
               {: RESULT = new UnaryExpr(UnaryExpr.UMINUS, e, loc(eleft, eright)); :}
               %prec UMINUS
            ;
            